extends Node

enum dir {LEFT, RIGHT, UP, DOWN, TOPLEFT, TOPRIGHT, BOTLEFT, BOTRIGHT}

enum DamageType {NONE, BEAM, BOMB, POWERBOMB, MISSILE, SUPERMISSILE, SCREWATTACK, SPEEDBOOSTER, CRUMBLE, SPIKE}

enum Upgrade {
	
	# Amount-based
	ETANK,
	MISSILE,
	SUPERMISSILE, 
	POWERBOMB, 
	
	# Misc unique
	BOMB, 
	MORPHBALL, 
	SPIDERBALL, 
	SPRINGBALL, 
	POWERGRIP, 
	HIGHJUMP, 
	SPACEJUMP, 
	SCREWATTACK, 
	SPEEDBOOSTER, 
	
	# Suits
	POWERSUIT,
	VARIASUIT, 
	GRAVITYSUIT, 
	
	# Power beams
	POWERBEAM, 
	ICEBEAM, 
	PLASMABEAM, 
	SPAZERBEAM, 
	WAVEBEAM, 
	
	# Other beams
	CHARGEBEAM, 
	GRAPPLEBEAM,
	
	# Visors
	SCANVISOR, 
	XRAYVISOR,
	
}
const UpgradeTypes: = {
	"visor": [Upgrade.XRAYVISOR, Upgrade.SCANVISOR],
	"beam": [Upgrade.POWERBEAM, Upgrade.ICEBEAM, Upgrade.PLASMABEAM, Upgrade.SPAZERBEAM, Upgrade.WAVEBEAM],
	"suit": [Upgrade.POWERSUIT, Upgrade.VARIASUIT, Upgrade.GRAVITYSUIT],
	}
const upgrade_gain_amounts = {
	Upgrade.MISSILE: 5,
	Upgrade.SUPERMISSILE: 5,
	Upgrade.POWERBOMB: 5,
}

enum Layers {ENEMY, SAMUS, WORLD, BLOCK, DOOR, PROJECTILE, FLUID, VISOR, MENU, NOTIFICATION}
enum CanvasLayers {HUD, MENU, NOTIFICATION}
